//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hotel.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Додати бронювання.
        /// </summary>
        internal static string AddBooking {
            get {
                return ResourceManager.GetString("AddBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Створення нового бронювання.
        /// </summary>
        internal static string AddBookingTitle {
            get {
                return ResourceManager.GetString("AddBookingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Додати гостя.
        /// </summary>
        internal static string AddGuest {
            get {
                return ResourceManager.GetString("AddGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введіть дані гостя.
        /// </summary>
        internal static string AddGuestTitle {
            get {
                return ResourceManager.GetString("AddGuestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Система управління готелем.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Гостя з таким номером не знайдено. Бажаєте додати нового гостя зараз?.
        /// </summary>
        internal static string Booking_AskCreateGuest_Msg {
            get {
                return ResourceManager.GetString("Booking_AskCreateGuest_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Гість не знайдений.
        /// </summary>
        internal static string Booking_AskCreateGuest_Title {
            get {
                return ResourceManager.GetString("Booking_AskCreateGuest_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступні номери:.
        /// </summary>
        internal static string Booking_AvailableRooms {
            get {
                return ResourceManager.GetString("Booking_AvailableRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скасувати.
        /// </summary>
        internal static string Booking_Cancel {
            get {
                return ResourceManager.GetString("Booking_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ви дійсно хочете скасувати це бронювання?.
        /// </summary>
        internal static string Booking_CancelConfirm {
            get {
                return ResourceManager.GetString("Booking_CancelConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заселити.
        /// </summary>
        internal static string Booking_CheckIn {
            get {
                return ResourceManager.GetString("Booking_CheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Виселити.
        /// </summary>
        internal static string Booking_CheckOut {
            get {
                return ResourceManager.GetString("Booking_CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Знайти гостя.
        /// </summary>
        internal static string Booking_FindGuest {
            get {
                return ResourceManager.GetString("Booking_FindGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Знайти вільні номери.
        /// </summary>
        internal static string Booking_FindRooms {
            get {
                return ResourceManager.GetString("Booking_FindRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Інформація про гостя.
        /// </summary>
        internal static string Booking_GuestInfo {
            get {
                return ResourceManager.GetString("Booking_GuestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ім&apos;я гостя:.
        /// </summary>
        internal static string Booking_GuestName {
            get {
                return ResourceManager.GetString("Booking_GuestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Гостя з таким номером телефону не знайдено..
        /// </summary>
        internal static string Booking_GuestNotFound {
            get {
                return ResourceManager.GetString("Booking_GuestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На жаль, вільних номерів на ці дати/кількість гостей не знайдено..
        /// </summary>
        internal static string Booking_NoRoomsFound {
            get {
                return ResourceManager.GetString("Booking_NoRoomsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кількість гостей:.
        /// </summary>
        internal static string Booking_NumGuests {
            get {
                return ResourceManager.GetString("Booking_NumGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Всього ночей: {0}.
        /// </summary>
        internal static string Booking_NumNights {
            get {
                return ResourceManager.GetString("Booking_NumNights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на -- Спочатку знайдіть номери --.
        /// </summary>
        internal static string Booking_SelectRoom {
            get {
                return ResourceManager.GetString("Booking_SelectRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЗАГАЛЬНА ВАРТІСТЬ:.
        /// </summary>
        internal static string Booking_TotalPrice {
            get {
                return ResourceManager.GetString("Booking_TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редагувати.
        /// </summary>
        internal static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Розрахувати.
        /// </summary>
        internal static string ButtonCalculate {
            get {
                return ResourceManager.GetString("ButtonCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скасувати.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистити.
        /// </summary>
        internal static string ButtonClear {
            get {
                return ResourceManager.GetString("ButtonClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Звіт.
        /// </summary>
        internal static string ButtonReport {
            get {
                return ResourceManager.GetString("ButtonReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скинути.
        /// </summary>
        internal static string ButtonReset {
            get {
                return ResourceManager.GetString("ButtonReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зберегти.
        /// </summary>
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пошук.
        /// </summary>
        internal static string ButtonSearch {
            get {
                return ResourceManager.GetString("ButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Розрахувати вартість.
        /// </summary>
        internal static string CalculatePrice {
            get {
                return ResourceManager.GetString("CalculatePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Розрахунок вартості проживання.
        /// </summary>
        internal static string CalculatePriceTitle {
            get {
                return ResourceManager.GetString("CalculatePriceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перевірити доступність.
        /// </summary>
        internal static string CheckAvailability {
            get {
                return ResourceManager.GetString("CheckAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перевірка доступних номерів.
        /// </summary>
        internal static string CheckAvailabilityTitle {
            get {
                return ResourceManager.GetString("CheckAvailabilityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата народження.
        /// </summary>
        internal static string Col_BirthDate {
            get {
                return ResourceManager.GetString("Col_BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер бронювання.
        /// </summary>
        internal static string Col_BookingID {
            get {
                return ResourceManager.GetString("Col_BookingID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата заїзду.
        /// </summary>
        internal static string Col_CheckIn {
            get {
                return ResourceManager.GetString("Col_CheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата виїзду.
        /// </summary>
        internal static string Col_CheckOut {
            get {
                return ResourceManager.GetString("Col_CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ім&apos;я.
        /// </summary>
        internal static string Col_FirstName {
            get {
                return ResourceManager.GetString("Col_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ім&apos;я гостя.
        /// </summary>
        internal static string Col_GuestName {
            get {
                return ResourceManager.GetString("Col_GuestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер гостя.
        /// </summary>
        internal static string Col_ID {
            get {
                return ResourceManager.GetString("Col_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Постійний клієнт.
        /// </summary>
        internal static string Col_IsRegular {
            get {
                return ResourceManager.GetString("Col_IsRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прізвище.
        /// </summary>
        internal static string Col_LastName {
            get {
                return ResourceManager.GetString("Col_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кількість гостей.
        /// </summary>
        internal static string Col_NumGuests {
            get {
                return ResourceManager.GetString("Col_NumGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Паспорт.
        /// </summary>
        internal static string Col_Passport {
            get {
                return ResourceManager.GetString("Col_Passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон.
        /// </summary>
        internal static string Col_Phone {
            get {
                return ResourceManager.GetString("Col_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ціна за ніч.
        /// </summary>
        internal static string Col_PricePerNight {
            get {
                return ResourceManager.GetString("Col_PricePerNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер кімнати.
        /// </summary>
        internal static string Col_RoomID {
            get {
                return ResourceManager.GetString("Col_RoomID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип кімнати.
        /// </summary>
        internal static string Col_RoomType {
            get {
                return ResourceManager.GetString("Col_RoomType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        internal static string Col_Status {
            get {
                return ResourceManager.GetString("Col_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступно:.
        /// </summary>
        internal static string Dashboard_Available {
            get {
                return ResourceManager.GetString("Dashboard_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сьогоднішні заселення ({0}).
        /// </summary>
        internal static string Dashboard_CheckIns {
            get {
                return ResourceManager.GetString("Dashboard_CheckIns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сьогоднішні виселення ({0}).
        /// </summary>
        internal static string Dashboard_CheckOuts {
            get {
                return ResourceManager.GetString("Dashboard_CheckOuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На прибиранні:.
        /// </summary>
        internal static string Dashboard_Cleaning {
            get {
                return ResourceManager.GetString("Dashboard_Cleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Гість.
        /// </summary>
        internal static string Dashboard_Guest {
            get {
                return ResourceManager.GetString("Dashboard_Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зайнято:.
        /// </summary>
        internal static string Dashboard_Occupied {
            get {
                return ResourceManager.GetString("Dashboard_Occupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На ремонті:.
        /// </summary>
        internal static string Dashboard_Repair {
            get {
                return ResourceManager.GetString("Dashboard_Repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стан кімнат.
        /// </summary>
        internal static string Dashboard_RoomStatus {
            get {
                return ResourceManager.GetString("Dashboard_RoomStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Інформаційна панель.
        /// </summary>
        internal static string Dashboard_Title {
            get {
                return ResourceManager.GetString("Dashboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редагування даних гостя.
        /// </summary>
        internal static string EditGuest_Title {
            get {
                return ResourceManager.GetString("EditGuest_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Англійська.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Помилка бази даних.
        /// </summary>
        internal static string ErrorDBTitle {
            get {
                return ResourceManager.GetString("ErrorDBTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дані гостя успішно оновлено!.
        /// </summary>
        internal static string Guest_Update_Success {
            get {
                return ResourceManager.GetString("Guest_Update_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус бронювання:.
        /// </summary>
        internal static string LabelBookingStatus {
            get {
                return ResourceManager.GetString("LabelBookingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата реєстрації:.
        /// </summary>
        internal static string LabelCheckIn {
            get {
                return ResourceManager.GetString("LabelCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата виїзду:.
        /// </summary>
        internal static string LabelCheckOut {
            get {
                return ResourceManager.GetString("LabelCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата народження:.
        /// </summary>
        internal static string LabelDateOfBirth {
            get {
                return ResourceManager.GetString("LabelDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ім&apos;я:.
        /// </summary>
        internal static string LabelFirstName {
            get {
                return ResourceManager.GetString("LabelFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на З:.
        /// </summary>
        internal static string LabelFrom {
            get {
                return ResourceManager.GetString("LabelFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер гостя:.
        /// </summary>
        internal static string LabelGuestID {
            get {
                return ResourceManager.GetString("LabelGuestID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прізвище:.
        /// </summary>
        internal static string LabelLastName {
            get {
                return ResourceManager.GetString("LabelLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новий статус:.
        /// </summary>
        internal static string LabelNewStatus {
            get {
                return ResourceManager.GetString("LabelNewStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Серія паспорту:.
        /// </summary>
        internal static string LabelPassport {
            get {
                return ResourceManager.GetString("LabelPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер телефону:.
        /// </summary>
        internal static string LabelPhoneNumber {
            get {
                return ResourceManager.GetString("LabelPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результат (грн):.
        /// </summary>
        internal static string LabelResult {
            get {
                return ResourceManager.GetString("LabelResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер кімнати:.
        /// </summary>
        internal static string LabelRoomID {
            get {
                return ResourceManager.GetString("LabelRoomID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пошук:.
        /// </summary>
        internal static string LabelSearch {
            get {
                return ResourceManager.GetString("LabelSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сортувати:.
        /// </summary>
        internal static string LabelSort {
            get {
                return ResourceManager.GetString("LabelSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По:.
        /// </summary>
        internal static string LabelTo {
            get {
                return ResourceManager.GetString("LabelTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мова.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список бронювань.
        /// </summary>
        internal static string ListBookings {
            get {
                return ResourceManager.GetString("ListBookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список бронювань.
        /// </summary>
        internal static string ListBookingsTitle {
            get {
                return ResourceManager.GetString("ListBookingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список гостей.
        /// </summary>
        internal static string ListGuests {
            get {
                return ResourceManager.GetString("ListGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список зареєстрованих гостей.
        /// </summary>
        internal static string ListGuestsTitle {
            get {
                return ResourceManager.GetString("ListGuestsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список кімнат.
        /// </summary>
        internal static string ListRooms {
            get {
                return ResourceManager.GetString("ListRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список кімнат готелю.
        /// </summary>
        internal static string ListRoomsTitle {
            get {
                return ResourceManager.GetString("ListRoomsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Увійти.
        /// </summary>
        internal static string Login_Button {
            get {
                return ResourceManager.GetString("Login_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не вдалося підключитися до бази даних:.
        /// </summary>
        internal static string Login_Error_Connection {
            get {
                return ResourceManager.GetString("Login_Error_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Помилка підключення.
        /// </summary>
        internal static string Login_Error_ConnectionTitle {
            get {
                return ResourceManager.GetString("Login_Error_ConnectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неправильне ім&apos;я користувача або пароль..
        /// </summary>
        internal static string Login_Error_Invalid {
            get {
                return ResourceManager.GetString("Login_Error_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Помилка входу.
        /// </summary>
        internal static string Login_Error_Title {
            get {
                return ResourceManager.GetString("Login_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль:.
        /// </summary>
        internal static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авторизація.
        /// </summary>
        internal static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Користувач:.
        /// </summary>
        internal static string Login_Username {
            get {
                return ResourceManager.GetString("Login_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Будь ласка, введіть ім&apos;я користувача та пароль..
        /// </summary>
        internal static string Login_Validation_Empty {
            get {
                return ResourceManager.GetString("Login_Validation_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ви точно бажаєте вийти із системи?.
        /// </summary>
        internal static string Logout_Confirm_Text {
            get {
                return ResourceManager.GetString("Logout_Confirm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вихід із системи.
        /// </summary>
        internal static string Logout_Confirm_Title {
            get {
                return ResourceManager.GetString("Logout_Confirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Налаштування мови буде застосовано після перезапуску..
        /// </summary>
        internal static string MsgLanguageRestart {
            get {
                return ResourceManager.GetString("MsgLanguageRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зміна мови.
        /// </summary>
        internal static string MsgLanguageTitle {
            get {
                return ResourceManager.GetString("MsgLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Немає даних для генерації звіту..
        /// </summary>
        internal static string MsgNoDataForReport {
            get {
                return ResourceManager.GetString("MsgNoDataForReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адміністратор.
        /// </summary>
        internal static string Role_Administrator {
            get {
                return ResourceManager.GetString("Role_Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рецепціоніст.
        /// </summary>
        internal static string Role_Receptionist {
            get {
                return ResourceManager.GetString("Role_Receptionist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невідома роль.
        /// </summary>
        internal static string Role_Unknown {
            get {
                return ResourceManager.GetString("Role_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Налаштування.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Налаштування.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на За датою заїзду (старіші).
        /// </summary>
        internal static string Sort_Booking_Date_ASC {
            get {
                return ResourceManager.GetString("Sort_Booking_Date_ASC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на За датою заїзду (новіші).
        /// </summary>
        internal static string Sort_Booking_Date_DESC {
            get {
                return ResourceManager.GetString("Sort_Booking_Date_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на За ID бронювання.
        /// </summary>
        internal static string Sort_Booking_ID {
            get {
                return ResourceManager.GetString("Sort_Booking_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на За ID (зростання).
        /// </summary>
        internal static string Sort_Guest_ID_ASC {
            get {
                return ResourceManager.GetString("Sort_Guest_ID_ASC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на За ID (спадання).
        /// </summary>
        internal static string Sort_Guest_ID_DESC {
            get {
                return ResourceManager.GetString("Sort_Guest_ID_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на За прізвищем (А-Я).
        /// </summary>
        internal static string Sort_Guest_LastName_ASC {
            get {
                return ResourceManager.GetString("Sort_Guest_LastName_ASC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на За прізвищем (Я-А).
        /// </summary>
        internal static string Sort_Guest_LastName_DESC {
            get {
                return ResourceManager.GetString("Sort_Guest_LastName_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на За номером (зростання).
        /// </summary>
        internal static string Sort_Room_ID_ASC {
            get {
                return ResourceManager.GetString("Sort_Room_ID_ASC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на За номером (спадання).
        /// </summary>
        internal static string Sort_Room_ID_DESC {
            get {
                return ResourceManager.GetString("Sort_Room_ID_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на За статусом (Доступні спочатку).
        /// </summary>
        internal static string Sort_Room_Status_Available {
            get {
                return ResourceManager.GetString("Sort_Room_Status_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на За статусом (На прибиранні спочатку).
        /// </summary>
        internal static string Sort_Room_Status_Cleaning {
            get {
                return ResourceManager.GetString("Sort_Room_Status_Cleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на За статусом (На ремонті спочатку).
        /// </summary>
        internal static string Sort_Room_Status_Repair {
            get {
                return ResourceManager.GetString("Sort_Room_Status_Repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на За типом (А-Я).
        /// </summary>
        internal static string Sort_Room_Type_ASC {
            get {
                return ResourceManager.GetString("Sort_Room_Type_ASC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на За типом (Я-А).
        /// </summary>
        internal static string Sort_Room_Type_DESC {
            get {
                return ResourceManager.GetString("Sort_Room_Type_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступна.
        /// </summary>
        internal static string Status_Available {
            get {
                return ResourceManager.GetString("Status_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скасовано.
        /// </summary>
        internal static string Status_Booking_Cancelled {
            get {
                return ResourceManager.GetString("Status_Booking_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Підтверджено.
        /// </summary>
        internal static string Status_Booking_Confirmed {
            get {
                return ResourceManager.GetString("Status_Booking_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скасовано.
        /// </summary>
        internal static string Status_Cancelled {
            get {
                return ResourceManager.GetString("Status_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На прибиранні.
        /// </summary>
        internal static string Status_Cleaning {
            get {
                return ResourceManager.GetString("Status_Cleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершено.
        /// </summary>
        internal static string Status_Completed {
            get {
                return ResourceManager.GetString("Status_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проживає.
        /// </summary>
        internal static string Status_Living {
            get {
                return ResourceManager.GetString("Status_Living", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зайнята.
        /// </summary>
        internal static string Status_Occupied {
            get {
                return ResourceManager.GetString("Status_Occupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На ремонті.
        /// </summary>
        internal static string Status_Repair {
            get {
                return ResourceManager.GetString("Status_Repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Українська.
        /// </summary>
        internal static string Ukrainian {
            get {
                return ResourceManager.GetString("Ukrainian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оновити статус номерів.
        /// </summary>
        internal static string UpdateRoomStatus {
            get {
                return ResourceManager.GetString("UpdateRoomStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оновлення статусу кімнати.
        /// </summary>
        internal static string UpdateRoomStatusTitle {
            get {
                return ResourceManager.GetString("UpdateRoomStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Гість з таким номером паспорта вже існує..
        /// </summary>
        internal static string Validation_PassportExists {
            get {
                return ResourceManager.GetString("Validation_PassportExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Гість з таким номером телефону вже існує..
        /// </summary>
        internal static string Validation_PhoneExists {
            get {
                return ResourceManager.GetString("Validation_PhoneExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата виїзду повинна бути пізніше дати заїзду..
        /// </summary>
        internal static string ValidationDateError {
            get {
                return ResourceManager.GetString("ValidationDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID гостя та кімнати повинні бути числами..
        /// </summary>
        internal static string ValidationIdError {
            get {
                return ResourceManager.GetString("ValidationIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ім&apos;я та Прізвище є обов&apos;язковими полями..
        /// </summary>
        internal static string ValidationNamesRequired {
            get {
                return ResourceManager.GetString("ValidationNamesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Серію паспорту введено неправильно. Допустимі формати: 9 цифр (ID) або 2 літери та 6 цифр (книжечка)..
        /// </summary>
        internal static string ValidationPassportFormat {
            get {
                return ResourceManager.GetString("ValidationPassportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер телефону введено неправильно. Допустимі формати: +380... (13) або 0... (10)..
        /// </summary>
        internal static string ValidationPhoneFormat {
            get {
                return ResourceManager.GetString("ValidationPhoneFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Будь ласка, виберіть статус..
        /// </summary>
        internal static string ValidationStatusError {
            get {
                return ResourceManager.GetString("ValidationStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Помилка валідації.
        /// </summary>
        internal static string ValidationTitle {
            get {
                return ResourceManager.GetString("ValidationTitle", resourceCulture);
            }
        }
    }
}
